trigger:
- master

pool: Default

steps:

- script: dotnet build MvcTest
  displayName: Build

# - script: dotnet publish MvcTest -o ../publish
#   displayName: 'dotnet publish'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/MvcTest.csproj'
    arguments: --no-build --output $(Build.ArtifactStagingDirectory)
    modifyOutputPath: false

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service deploy'
  inputs:
    azureSubscription: nick-azure
    WebAppName: escalona1902test
    packageForLinux: $(Build.ArtifactStagingDirectory)
    removeAdditionalFilesFlag: true
