trigger:
- master

pool:Default

steps:

# - script: dotnet publish MvcTest -o ../publish
#   displayName: 'dotnet publish'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: MvcTest
    arguments: -o publish
    modifyOutputPath: false

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service deploy'
  inputs:
    azureSubscription: nick-azure
    WebAppName: escalona1902test
    packageForLinux: publish